title: Mitchell’s Guide to Open Source Subcultures
url: https://culture.kemitchell.com
homepage: https://culture.kemitchell.com
description: overview of philosophies, movements, and schools of thought
exclude:
  - README.md
